service: gptsbot
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
functions:
  receive:
    handler: handler.receive
    events:
      - http:
          path: receive
          method: post
